In [1]:
import sys
print(sys.executable)

C:\Users\Salvatore\anaconda3\envs\marketing\python.exe

In [2]:
import pandas as pd
import numpy as np

In [3]:
file_path = "data/Online Retail.xlsx"

df = pd.read_excel(file_path)

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
df.shape

(541909, 8)

In [5]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [7]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [8]:
df[df["Quantity"] < 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom

In [9]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [10]:
df = df.dropna(subset=["CustomerID"])

In [11]:
df["CustomerID"].isnull().sum()

np.int64(0)

In [12]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
Revenue        0
dtype: int64

In [13]:
df["CustomerID"] = df["CustomerID"].astype(int)

In [14]:
df = df[df["Quantity"] > 0]

In [15]:
df = df[df["UnitPrice"] > 0]

In [16]:
df.duplicated().sum()

np.int64(5192)

In [17]:
df = df.drop_duplicates()

In [18]:
df["InvoiceDate"].min(), df["InvoiceDate"].max()

(Timestamp('2010-12-01 08:26:00'), Timestamp('2011-12-09 12:50:00'))

In [19]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 392692 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    392692 non-null  object
 1   StockCode    392692 non-null  object
 2   Description  392692 non-null  object
 3   Quantity     392692 non-null  int64
 4   InvoiceDate  392692 non-null  datetime64[ns]
 5   UnitPrice    392692 non-null  float64
 6   CustomerID   392692 non-null  int64
 7   Country      392692 non-null  object
 8   Revenue      392692 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 30.0+ MB

,Quantity,InvoiceDate,UnitPrice,CustomerID,Revenue
count,392692.000000,392692,392692.000000,392692.000000,392692.000000
mean,13.119702,2011-07-10 19:13:07.771892480,3.125914,15287.843865,22.631500
min,1.000000,2010-12-01 08:26:00,0.001000,12346.000000,0.001000
25%,2.000000,2011-04-07 11:12:00,1.250000,13955.000000,4.950000
50%,6.000000,2011-07-31 12:02:00,1.950000,15150.000000,12.450000
75%,12.000000,2011-10-20 12:53:00,3.750000,16791.000000,19.800000
max,80995.000000,2011-12-09 12:50:00,8142.750000,18287.000000,168469.600000
std,180.492832,NaN,22.241836,1713.539549,311.099224

In [20]:
df["CustomerID"].nunique()

4338

In [21]:
orders_per_customer = df.groupby("CustomerID")["InvoiceNo"].nunique()

orders_per_customer.head()

CustomerID
12346    1
12347    7
12348    4
12349    1
12350    1
Name: InvoiceNo, dtype: int64

In [22]:
revenue_per_customer = df.groupby("CustomerID")["Revenue"].sum()

revenue_per_customer.head()

CustomerID
12346    77183.60
12347     4310.00
12348     1797.24
12349     1757.55
12350      334.40
Name: Revenue, dtype: float64

In [23]:
items_per_customer = df.groupby("CustomerID")["Quantity"].sum()

items_per_customer.head()

CustomerID
12346    74215
12347     2458
12348     2341
12349      631
12350      197
Name: Quantity, dtype: int64

In [24]:
last_purchase = df.groupby("CustomerID")["InvoiceDate"].max()

last_purchase.head()

CustomerID
12346   2011-01-18 10:01:00
12347   2011-12-07 15:52:00
12348   2011-09-25 13:13:00
12349   2011-11-21 09:51:00
12350   2011-02-02 16:01:00
Name: InvoiceDate, dtype: datetime64[ns]

In [25]:
first_purchase = df.groupby("CustomerID")["InvoiceDate"].min()

first_purchase.head()

CustomerID
12346   2011-01-18 10:01:00
12347   2010-12-07 14:57:00
12348   2010-12-16 19:09:00
12349   2011-11-21 09:51:00
12350   2011-02-02 16:01:00
Name: InvoiceDate, dtype: datetime64[ns]

In [26]:
customer_df = df.groupby("CustomerID").agg({
    "InvoiceNo": "nunique",
    "Revenue": "sum",
    "Quantity": "sum",
    "InvoiceDate": ["min", "max"]
})

In [27]:
customer_df.columns = [
    "num_orders",
    "total_revenue",
    "total_items",
    "first_purchase",
    "last_purchase"
]

In [28]:
customer_df.head()

,num_orders,total_revenue,total_items,first_purchase,last_purchase
CustomerID,,,,,
12346,1,77183.60,74215,2011-01-18 10:01:00,2011-01-18 10:01:00
12347,7,4310.00,2458,2010-12-07 14:57:00,2011-12-07 15:52:00
12348,4,1797.24,2341,2010-12-16 19:09:00,2011-09-25 13:13:00
12349,1,1757.55,631,2011-11-21 09:51:00,2011-11-21 09:51:00
12350,1,334.40,197,2011-02-02 16:01:00,2011-02-02 16:01:00

In [29]:
customer_df.shape

(4338, 5)

In [30]:
analysis_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)

analysis_date

Timestamp('2011-12-10 12:50:00')

In [31]:
customer_df["recency"] = (analysis_date - customer_df["last_purchase"]).dt.days

In [32]:
customer_df["frequency"] = customer_df["num_orders"]

In [33]:
customer_df["monetary"] = customer_df["total_revenue"]

In [34]:
customer_df[["recency", "frequency", "monetary"]].head()

            recency  frequency  monetary
CustomerID
12346           326          1  77183.60
12347             2          7   4310.00
12348            75          4   1797.24
12349            19          1   1757.55
12350           310          1    334.40

In [35]:
customer_df["R_score"] = pd.qcut(customer_df["recency"], 5, labels=[5,4,3,2,1])

In [36]:
customer_df["F_score"] = pd.qcut(customer_df["frequency"].rank(method="first"), 5, labels=[1,2,3,4,5])

In [37]:
customer_df["M_score"] = pd.qcut(customer_df["monetary"], 5, labels=[1,2,3,4,5])

In [38]:
customer_df["RFM_score"] = (
    customer_df["R_score"].astype(str) +
    customer_df["F_score"].astype(str) +
    customer_df["M_score"].astype(str)
)

In [39]:
customer_df["RFM_score"].value_counts().head(10)

RFM_score
555    347
111    183
455    177
121    153
112    127
444    118
122     90
544     85
233     83
344     82
Name: count, dtype: int64

In [40]:
customer_df.to_csv("rfm_results.csv")